/**
 * Money Flow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Category { 
    id: string;
    name: string;
    type: Category.TypeEnum;
    color: string;
}
export namespace Category {
    export const TypeEnum = {
        Expense: 'expense',
        Income: 'income'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


