/**
 * Money Flow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Transaction { 
    id: string;
    categoryId: string;
    amount: number;
    date: string;
    description?: string | null;
}

