/**
 * Money Flow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateTransaction { 
    categoryId?: string;
    amount?: number;
    date?: string;
    description?: string;
}

