/**
 * Money Flow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateCategory { 
    name?: string;
    type?: UpdateCategory.TypeEnum;
    color?: string;
}
export namespace UpdateCategory {
    export const TypeEnum = {
        Expense: 'expense',
        Income: 'income'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


